// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"math/big"
)

type Collection struct {
	Address     string   `json:"address"`
	Name        string   `json:"name"`
	Symbol      string   `json:"symbol"`
	Description string   `json:"description"`
	Image       string   `json:"image"`
	Banner      string   `json:"banner"`
	Website     string   `json:"website"`
	Twitter     string   `json:"twitter"`
	Discord     string   `json:"discord"`
	Slug        string   `json:"slug"`
	Category    string   `json:"category"`
	IsVerified  bool     `json:"isVerified"`
	IsBlocked   bool     `json:"isBlocked"`
	FloorPrice  *big.Int `json:"floorPrice,omitempty"`
	BestBid     *big.Int `json:"bestBid,omitempty"`
	ListedCount int      `json:"listedCount"`
	CreatedAt   string   `json:"createdAt"`
}

type CollectionConnection struct {
	Collections []*Collection `json:"collections"`
	Total       int           `json:"total"`
	Page        int           `json:"page"`
	PageSize    int           `json:"pageSize"`
}

type CollectionStats struct {
	FloorPrice  *big.Int `json:"floorPrice,omitempty"`
	BestBid     *big.Int `json:"bestBid,omitempty"`
	ListedCount int      `json:"listedCount"`
}

type GlobalStats struct {
	TotalOrders      int `json:"totalOrders"`
	TotalCollections int `json:"totalCollections"`
	TotalTraders     int `json:"totalTraders"`
}

type Mutation struct {
}

type Order struct {
	Hash         string   `json:"hash"`
	Maker        string   `json:"maker"`
	Taker        *string  `json:"taker,omitempty"`
	Side         int      `json:"side"`
	Kind         int      `json:"kind"`
	AssetType    int      `json:"assetType"`
	Collection   string   `json:"collection"`
	TokenID      *big.Int `json:"tokenId"`
	Amount       *big.Int `json:"amount"`
	Price        *big.Int `json:"price"`
	StartPrice   *big.Int `json:"startPrice,omitempty"`
	StartTime    string   `json:"startTime"`
	EndTime      string   `json:"endTime"`
	Salt         *big.Int `json:"salt"`
	Signature    string   `json:"signature"`
	Status       int      `json:"status"`
	Counter      *big.Int `json:"counter"`
	CurrentPrice *big.Int `json:"currentPrice"`
	Extra        string   `json:"extra"`
	CreatedAt    string   `json:"createdAt"`
}

type OrderConnection struct {
	Orders   []*Order `json:"orders"`
	Total    int      `json:"total"`
	Page     int      `json:"page"`
	PageSize int      `json:"pageSize"`
}

type OrderFilter struct {
	Collection *string `json:"collection,omitempty"`
	Maker      *string `json:"maker,omitempty"`
	Side       *int    `json:"side,omitempty"`
	Kind       *int    `json:"kind,omitempty"`
	AssetType  *int    `json:"assetType,omitempty"`
	Status     *int    `json:"status,omitempty"`
	MinPrice   *string `json:"minPrice,omitempty"`
	MaxPrice   *string `json:"maxPrice,omitempty"`
}

type Query struct {
}

type SubmitOrderInput struct {
	Maker        string  `json:"maker"`
	Taker        *string `json:"taker,omitempty"`
	Side         int     `json:"side"`
	Kind         int     `json:"kind"`
	AssetType    int     `json:"assetType"`
	Collection   string  `json:"collection"`
	TokenID      string  `json:"tokenId"`
	Amount       string  `json:"amount"`
	Price        string  `json:"price"`
	PaymentToken *string `json:"paymentToken,omitempty"`
	StartPrice   *string `json:"startPrice,omitempty"`
	StartTime    int     `json:"startTime"`
	EndTime      int     `json:"endTime"`
	Salt         string  `json:"salt"`
	Signature    string  `json:"signature"`
	Extra        *string `json:"extra,omitempty"`
}
