package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
)

// SubmitOrder is the resolver for the submitOrder field.
func (r *mutationResolver) SubmitOrder(ctx context.Context, input SubmitOrderInput) (*Order, error) {
	panic(fmt.Errorf("not implemented: SubmitOrder - submitOrder"))
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, hash string) (*Order, error) {
	panic(fmt.Errorf("not implemented: Order - order"))
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, filter *OrderFilter, page int, pageSize int) (*OrderConnection, error) {
	panic(fmt.Errorf("not implemented: Orders - orders"))
}

// BestOrder is the resolver for the bestOrder field.
func (r *queryResolver) BestOrder(ctx context.Context, collection string, side int) (*Order, error) {
	panic(fmt.Errorf("not implemented: BestOrder - bestOrder"))
}

// Collection is the resolver for the collection field.
func (r *queryResolver) Collection(ctx context.Context, address string) (*Collection, error) {
	panic(fmt.Errorf("not implemented: Collection - collection"))
}

// Collections is the resolver for the collections field.
func (r *queryResolver) Collections(ctx context.Context, search *string, page int, pageSize int) (*CollectionConnection, error) {
	panic(fmt.Errorf("not implemented: Collections - collections"))
}

// UserOrders is the resolver for the userOrders field.
func (r *queryResolver) UserOrders(ctx context.Context, address string, status []int, page int, pageSize int) (*OrderConnection, error) {
	panic(fmt.Errorf("not implemented: UserOrders - userOrders"))
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*GlobalStats, error) {
	panic(fmt.Errorf("not implemented: Stats - stats"))
}

// CollectionStats is the resolver for the collectionStats field.
func (r *queryResolver) CollectionStats(ctx context.Context, address string) (*CollectionStats, error) {
	panic(fmt.Errorf("not implemented: CollectionStats - collectionStats"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
